// Child is a profile under a Parent account.
// No email, no password, no personal data collected from the child directly.
// All data here is either entered by the parent or generated by the platform.

import mongoose from "mongoose";

// Available avatars — these are keys that map to avatar assets on the client
const AVATAR_OPTIONS = [
  "explorer",
  "scientist",
  "knight",
  "wizard",
  "astronaut",
  "ninja",
  "robot",
  "pirate",
];

const childSchema = new mongoose.Schema(
  {
    // Reference to the parent who owns this profile
    parent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Parent",
      required: true,
    },

    // First name only — entered by the parent, not the child
    firstName: {
      type: String,
      required: [true, "Child first name is required"],
      trim: true,
      maxlength: [50, "First name cannot exceed 50 characters"],
    },

    // Username chosen by the parent — shown to the child in the UI
    username: {
      type: String,
      required: [true, "Username is required"],
      unique: true,
      trim: true,
      lowercase: true,
      minlength: [3, "Username must be at least 3 characters"],
      maxlength: [20, "Username cannot exceed 20 characters"],
      match: [
        /^[a-z0-9_]+$/,
        "Username can only contain lowercase letters, numbers, and underscores",
      ],
    },

    // Age is stored to help the AI personalize content appropriately
    age: {
      type: Number,
      required: [true, "Age is required"],
      min: [6, "Age must be at least 6"],
      max: [17, "Age must be 17 or under"],
    },

    // Avatar key — maps to a visual asset on the frontend
    avatar: {
      type: String,
      enum: AVATAR_OPTIONS,
      default: "explorer",
    },

    // Daily time limit in minutes — 0 means no limit
    dailyTimeLimitMinutes: {
      type: Number,
      default: 60,
      min: 0,
      max: 480, // 8 hours maximum
    },

    // Gamification
    points: {
      type: Number,
      default: 0,
      min: 0,
    },

    level: {
      type: Number,
      default: 1,
      min: 1,
    },

    streakDays: {
      type: Number,
      default: 0,
      min: 0,
    },

    lastActivityDate: {
      type: Date,
      default: null,
    },

    // Current coding stage across the platform
    // Stage advances as the child completes chapters
    currentStage: {
      type: Number,
      default: 1,
      min: 1,
      max: 5,
    },

    // Stage titles map:
    // 1 = Visual Coder, 2 = Code Explorer, 3 = Bug Hunter,
    // 4 = Code Builder, 5 = Real Programmer

    // Whether this child profile is currently active
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// ── Virtual fields ────────────────────────────────────────────────────────

// Derive the stage title from the stage number
childSchema.virtual("stageTitle").get(function () {
  const titles = {
    1: "Visual Coder",
    2: "Code Explorer",
    3: "Bug Hunter",
    4: "Code Builder",
    5: "Real Programmer",
  };
  return titles[this.currentStage] || "Visual Coder";
});

// Make virtuals show up when converting to JSON (for API responses)
childSchema.set("toJSON", { virtuals: true });
childSchema.set("toObject", { virtuals: true });

const Child = mongoose.model("Child", childSchema);

export { AVATAR_OPTIONS };
export default Child;